
CHECK_SMALL_BAG_RECORDER_INTERVAL_SEC = 60
CHECK_FULL_BAG_RECORDER_INTERVAL_SEC = 60
CHECK_APOLLO_DATA_CLEANER_INTERVAL_SEC = 60
CHECK_EXTERNAL_DISK_DATA_SYNCHRONIZER_INTERVAL_SEC = 60
CHECK_EXTERNAL_DISK_DATA_CLEANER_INTERVAL_SEC = 60
UPDATE_EXTERNAL_DISK_LIST_INTERVAL_SEC = 60
CHECK_LOCATION_SPEED_RECORDER_INTERVAL_SEC = 60
CHECK_VARIOUS_RECORDER_SERVICE_INTERVAL_SEC = 60
CHECK_UDISK_MONITOR_INTERVAL_SEC = 60
CHECK_DATE_CHANGE_INTERVAL_SEC = 60

# full bag recorder policy
FORCE_START_FULL_BAG_RECORDER = "run full bag recorder forever"
FORCE_START_FULL_BAG_RECORDER_PATH = "/apollo/data/bag"
FORCE_STOP_FULL_BAG_RECORDER = "don't run full bag recorder forever"
AUTO_START_FULL_BAG_RECORDER = "if has external disk, start full bag recorder"
FULL_BAG_RECORDER_POLICY = AUTO_START_FULL_BAG_RECORDER
